const express = require('express');
const cors = require('cors');
const { spawn } = require('child_process');
const EventEmitter = require('events');
const path = require('path');
const fs = require('fs');
const XLSX = require('xlsx');
const { fetchClientData } = require('./test-db.js');

// Remove color-related environment variables to prevent warnings
// FORCE_COLOR and NO_COLOR conflict, causing Node.js warnings
if (process.env.FORCE_COLOR) {
  delete process.env.FORCE_COLOR;
}
if (process.env.NO_COLOR) {
  delete process.env.NO_COLOR;
}

// Create a log file stream for server logs
const logFilePath = path.join(__dirname, 'server.log');
const logStream = fs.createWriteStream(logFilePath, { flags: 'a' });

// Helper function to log to both console and file
function logToFile(level, message) {
  const timestamp = new Date().toISOString();
  const logMessage = `[${timestamp}] [${level}] ${message}\n`;
  logStream.write(logMessage);
  if (level === 'ERROR') {
    console.error(message);
  } else {
    console.log(message);
  }
}

// Check if node_modules exists, install if needed
const nodeModulesPath = path.join(__dirname, 'node_modules');
if (!fs.existsSync(nodeModulesPath)) {
    console.log('Installing dependencies...');
    const { execSync } = require('child_process');
    try {
        execSync('npm install', { stdio: 'inherit', cwd: __dirname });
        console.log('✅ Dependencies installed successfully');
    } catch (error) {
        console.error('❌ Failed to install dependencies:', error.message);
        process.exit(1);
    }
}

const app = express();
app.use(cors());
// Increase JSON body parser limit to handle large report data (100MB)
// Note: Chunked transfer is preferred for large reports, but we keep a high limit as fallback
app.use(express.json({ limit: '100mb' }));
app.use(express.urlencoded({ limit: '100mb', extended: true }));

const emitter = new EventEmitter();
let running = false;
let dbUpdateRunning = false;

// Helper function to generate HTML report template
function generateHtmlReport(clientName, clientId, reportData, timestamp, htmlTable, transferMethod = 'direct', transferTime = null) {
  const metadata = transferMethod === 'chunked' && transferTime
    ? `<p><strong>Transfer Method:</strong> Chunked (${transferTime})</p>`
    : '';
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${clientName} - Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }
        .container { max-width: 1400px; margin: 0 auto; background: white; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        h1 { color: #333; border-bottom: 3px solid #4CAF50; padding-bottom: 10px; }
        .metadata { background: #f9f9f9; padding: 15px; margin-bottom: 20px; border-radius: 5px; border-left: 4px solid #4CAF50; }
        .metadata p { margin: 5px 0; }
        table { border-collapse: collapse; width: 100%; margin-top: 20px; }
        table td, table th { border: 1px solid #ddd; padding: 10px; text-align: left; font-size: 14px; }
        table th { background-color: #4CAF50; color: white; font-weight: bold; position: sticky; top: 0; }
        table tr:nth-child(even) { background-color: #f9f9f9; }
        table tr:hover { background-color: #e8f5e9; }
        .footer { margin-top: 20px; text-align: center; color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>${clientName} - Employee Camera Hours Report</h1>
        <div class="metadata">
            <p><strong>Client ID:</strong> ${clientId || 'N/A'}</p>
            <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
            <p><strong>Total Rows:</strong> ${reportData.rowCount}</p>
            ${metadata}
            <p><strong>Timestamp:</strong> ${timestamp || new Date().toISOString()}</p>
        </div>
        ${htmlTable}
        <div class="footer">
            <p>Generated by Employee Camera Hours Dashboard</p>
        </div>
    </div>
</body>
</html>`;
}

// SSE endpoint: browser connects and receives log events
app.get('/events', (req, res) => {
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.flushHeaders();

  const onMessage = (msg) => {
    res.write(`data: ${JSON.stringify(msg)}\n\n`);
  };

  emitter.on('message', onMessage);

  // send a ping every 20s to keep connection alive
  const keepAlive = setInterval(() => res.write(':\n\n'), 20000);

  req.on('close', () => {
    clearInterval(keepAlive);
    emitter.off('message', onMessage);
  });
});

// Endpoint to start tests
app.post('/run-tests', (req, res) => {
  if (running) {
    return res.status(409).json({ error: 'Tests already running' });
  }

  // Get selected clients and dates from request body
  const selectedClients = req.body.clients || [];
  const startDate = req.body.startDate || '';
  const endDate = req.body.endDate || '';
  const reportType = req.body.reportType || 'summary';
  const reportName = req.body.reportName || 'employee-camera-hours';
  
  if (selectedClients.length === 0) {
    return res.status(400).json({ error: 'No clients selected for testing' });
  }
  
  // Validate that all clients have required fields
  const validClients = selectedClients.filter(client => {
    if (!client.applandingurl) {
      console.error(`❌ Client "${client.name}" missing applandingurl`);
      return false;
    }
    if (!client.liveserverip) {
      console.error(`❌ Client "${client.name}" missing liveserverip`);
      return false;
    }
    if (!client.dbname) {
      console.error(`❌ Client "${client.name}" missing dbname`);
      return false;
    }
    return true;
  });
  
  if (validClients.length === 0) {
    return res.status(400).json({ error: 'No clients with valid URLs selected for testing' });
  }
  
  if (validClients.length !== selectedClients.length) {
    console.log(`⚠️ ${selectedClients.length - validClients.length} clients skipped due to missing URLs`);
  }

  running = true;
  res.status(202).json({ status: 'started' });

  // Delete any existing Excel file at the start of a new test run
  const excelFileName = 'report-data.xlsx';
  const excelFilePath = path.join(__dirname, excelFileName);
  if (fs.existsSync(excelFilePath)) {
    fs.unlinkSync(excelFilePath);
  }

  console.log(`🎭 Starting Playwright tests for ${validClients.length} clients...`);
  if (startDate && endDate) {
    console.log(`📅 Using dates from UI - Start: ${startDate}, End: ${endDate}`);
  }
  console.log(`📊 Report Type: ${reportType}, Report Name: ${reportName}`);
  emitter.emit('message', { type: 'info', text: `Starting Playwright tests for ${validClients.length} clients...\n` });

  // Set environment variables with validated clients and dates
  // Create a clean copy of process.env and remove color-related vars to prevent warnings
  const env = {
    ...process.env
  };
  
  // Remove color-related environment variables to prevent warnings
  delete env.FORCE_COLOR;
  delete env.NO_COLOR;
  
  // Add our custom environment variables
  env.SELECTED_CLIENTS = JSON.stringify(validClients);
  env.START_DATE = startDate;
  env.END_DATE = endDate;
  env.REPORT_TYPE = reportType;
  env.REPORT_NAME = reportName;

  // Use playwright directly from node_modules to avoid npx overhead
  // This is faster than using npx which has to resolve and execute playwright each time
  const playwrightPath = path.join(__dirname, 'node_modules', '.bin', process.platform === 'win32' ? 'playwright.cmd' : 'playwright');
  
  // On Windows with shell: true, we need to properly quote paths with spaces
  // Use __dirname for cwd to ensure we're in the right directory (handles paths with spaces)
  const workingDir = __dirname;
  
  // For Windows with shell: true, construct the full command as a string to handle spaces properly
  let child;
  if (process.platform === 'win32') {
    // On Windows, quote the path and construct full command string
    const quotedPath = playwrightPath.includes(' ') ? `"${playwrightPath}"` : playwrightPath;
    const fullCommand = `${quotedPath} test --reporter=list`;
    child = spawn(fullCommand, [], { 
      shell: true,
      cwd: workingDir,
      env: env
    });
  } else {
    // On Unix-like systems, use array format
    child = spawn(playwrightPath, ['test', '--reporter=list'], { 
      shell: false,
      cwd: workingDir,
      env: env
    });
  }

  child.stdout.on('data', (d) => {
    const text = d.toString();
    console.log(text);
    logToFile('INFO', text.trim());
    emitter.emit('message', { type: 'stdout', text });
  });

  child.stderr.on('data', (d) => {
    const text = d.toString();
    console.error('⚠️ STDERR:', text);
    logToFile('ERROR', `STDERR: ${text.trim()}`);
    emitter.emit('message', { type: 'stderr', text });
  });

  child.on('close', (code) => {
    console.log(`🎭 Playwright tests completed with exit code: ${code}`);
    if (code !== 0) {
      console.error(`❌ Tests failed with exit code: ${code}`);
    }
    emitter.emit('message', { type: 'exit', code });
    emitter.emit('message', { type: 'info', text: `\nTests completed with exit code: ${code}\n` });
    running = false;
  });

  child.on('error', (err) => {
    console.error('❌ Playwright process error:', err.message);
    logToFile('ERROR', `Playwright process error: ${err.message}`);
    emitter.emit('message', { type: 'error', text: err.message });
    running = false;
  });
});

// Endpoint to update client data from database
app.post('/update-client-data', async (req, res) => {
  if (dbUpdateRunning) {
    return res.status(409).json({ error: 'Database update already running' });
  }

  dbUpdateRunning = true;
  res.status(202).json({ status: 'started', message: 'Database update initiated' });

  console.log('🔄 Starting automatic database update...');
  
  // Set a timeout for the database update
  const updateTimeout = setTimeout(() => {
    if (dbUpdateRunning) {
      console.error('⏱️  Database update timeout (30 seconds)');
      dbUpdateRunning = false;
      emitter.emit('message', { 
        type: 'error', 
        text: '⏱️  Database update timeout. Check VPN/network access.\n' 
      });
    }
  }, 35000); // 35 seconds timeout
  
  fetchClientData()
    .then((clientsData) => {
      clearTimeout(updateTimeout);
      console.log(`✅ Database update completed. Updated ${clientsData.length} clients.`);
      dbUpdateRunning = false;
      emitter.emit('message', { 
        type: 'info', 
        text: `✅ Database update completed. ${clientsData.length} clients updated.\n` 
      });
    })
    .catch((error) => {
      clearTimeout(updateTimeout);
      console.error('❌ Database update failed:', error.message);
      dbUpdateRunning = false;
      // Don't emit error if it's just a connection issue (expected when no VPN)
      if (!error.message.includes('timeout') && !error.message.includes('ECONNREFUSED')) {
        emitter.emit('message', { 
          type: 'error', 
          text: `❌ Database update failed: ${error.message}\n` 
        });
      }
    });
});

// Endpoint to receive report data from tests
app.post('/report-data', (req, res) => {
  try {
    const { clientName, clientId, reportData, timestamp, htmlTable } = req.body;
    
    // Log request size for debugging
    const requestSize = JSON.stringify(req.body).length;
    const requestSizeMB = (requestSize / (1024 * 1024)).toFixed(2);
    console.log(`📦 Received request for ${clientName}: ${requestSizeMB} MB`);
    
    // Check if we have any data (even just headers)
    if (!reportData || !reportData.headers || reportData.headers.length === 0) {
      console.log(`⚠️  No data to save for ${clientName}. No headers found.`);
      res.json({ status: 'received', message: 'No data - No headers found' });
      return;
    }
    
    // Log warning if no rows but continue to save headers
    if (!reportData.rows || reportData.rows.length === 0) {
      console.log(`⚠️  ${clientName}: No data rows found, but saving headers anyway...`);
    }
    
    console.log(`📊 Received report data for ${clientName}: ${reportData.rowCount} rows, ${reportData.headers.length} columns`);
    const excelFileName = 'report-data.xlsx';
    const excelFilePath = path.join(__dirname, excelFileName);
    
    if (fs.existsSync(excelFilePath)) {
      fs.unlinkSync(excelFilePath);
    }
    
    const worksheetData = [reportData.headers];
    reportData.rows.forEach(row => {
      const rowData = reportData.headers.map(header => row[header] || '');
      worksheetData.push(rowData);
    });
    
    const workbook = XLSX.utils.book_new();
    const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);
    
    const maxWidth = 50;
    const colWidths = reportData.headers.map(header => {
      const headerLength = header.length;
      const maxDataLength = reportData.rows.reduce((max, row) => {
        return Math.max(max, String(row[header] || '').length);
      }, headerLength);
      return { wch: Math.min(maxWidth, Math.max(headerLength, maxDataLength) + 2) };
    });
    worksheet['!cols'] = colWidths;
    
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Report Data');
    
    const metadataSheet = XLSX.utils.aoa_to_sheet([
      ['Client Name', clientName],
      ['Client ID', clientId || ''],
      ['Timestamp', timestamp || new Date().toISOString()],
      ['Total Rows', reportData.rowCount],
      ['Generated At', new Date().toLocaleString()]
    ]);
    XLSX.utils.book_append_sheet(workbook, metadataSheet, 'Metadata');
    
    XLSX.writeFile(workbook, excelFilePath);
    console.log(`✅ Excel file created: ${excelFileName} (${reportData.rowCount} rows)`);
    
    // Also save to JSON file in logs/json/portal directory
    const logsDir = path.join(__dirname, 'logs');
    if (!fs.existsSync(logsDir)) {
      fs.mkdirSync(logsDir, { recursive: true });
    }
    const jsonDir = path.join(logsDir, 'json', 'portal');
    if (!fs.existsSync(jsonDir)) {
      fs.mkdirSync(jsonDir, { recursive: true });
    }
    
    // Sanitize client name for filename
    const sanitizedClientName = clientName.replace(/[^a-zA-Z0-9]/g, '');
    const jsonFileName = `${sanitizedClientName}-report-${Date.now()}.json`;
    const jsonFilePath = path.join(jsonDir, jsonFileName);
    
    const jsonData = {
      clientName: clientName,
      clientId: clientId || '',
      timestamp: timestamp || new Date().toISOString(),
      generatedAt: new Date().toISOString(),
      totalRows: reportData.rowCount,
      headers: reportData.headers,
      data: reportData.rows
    };
    
    fs.writeFileSync(jsonFilePath, JSON.stringify(jsonData, null, 2), 'utf8');
    console.log(`✅ JSON file created: ${jsonFileName} (${reportData.rowCount} rows)`);
    console.log(`📁 JSON file path: ${jsonFilePath}`);
    
    // Save HTML table if provided
    if (htmlTable) {
      const htmlFileName = `${sanitizedClientName}-report-${Date.now()}.html`;
      const htmlFilePath = path.join(jsonDir, htmlFileName);
      const htmlContent = generateHtmlReport(clientName, clientId, reportData, timestamp, htmlTable);
      
      fs.writeFileSync(htmlFilePath, htmlContent, 'utf8');
      console.log(`✅ HTML file created: ${htmlFileName}`);
      console.log(`📁 HTML file path: ${htmlFilePath}`);
    }
    
    emitter.emit('message', { 
      type: 'info', 
      text: `📊 Excel file saved: ${excelFileName} (${reportData.rowCount} rows)\n📄 JSON file saved: ${jsonFileName} (${jsonFilePath})\n` 
    });
    
    emitter.emit('message', { 
      type: 'report-data', 
      clientName: clientName,
      clientId: clientId,
      reportData: reportData,
      timestamp: timestamp
    });
    
    res.json({ status: 'received', message: 'Report data received and saved to Excel and JSON', jsonFile: jsonFileName });
    
  } catch (error) {
    console.error('❌ Error saving Excel/JSON file:', error.message);
    logToFile('ERROR', `Error saving report data: ${error.message}`);
    emitter.emit('message', { 
      type: 'error', 
      text: `❌ Error saving report data: ${error.message}\n` 
    });
    res.status(500).json({ status: 'error', message: error.message });
  }
});

// In-memory storage for chunked data transfers
const chunkedDataStore = new Map();

// Cleanup stale sessions (older than 30 minutes)
setInterval(() => {
  const now = Date.now();
  const staleThreshold = 30 * 60 * 1000; // 30 minutes
  let cleaned = 0;
  
  for (const [sessionId, session] of chunkedDataStore.entries()) {
    if (now - session.startTime > staleThreshold) {
      chunkedDataStore.delete(sessionId);
      cleaned++;
      console.log(`🧹 Cleaned up stale chunked transfer session: ${sessionId}`);
    }
  }
  
  if (cleaned > 0) {
    console.log(`🧹 Cleaned up ${cleaned} stale chunked transfer session(s)`);
  }
}, 10 * 60 * 1000); // Run cleanup every 10 minutes

// Endpoint to initialize chunked data transfer
app.post('/report-data-chunk-start', (req, res) => {
  try {
    const { sessionId, clientName, clientId, headers, totalRows, timestamp } = req.body;
    
    if (!sessionId || !clientName || !headers) {
      return res.status(400).json({ status: 'error', message: 'Missing required fields' });
    }
    
    // Initialize chunk storage
    chunkedDataStore.set(sessionId, {
      clientName,
      clientId: clientId || '',
      headers,
      totalRows: totalRows || 0,
      timestamp: timestamp || new Date().toISOString(),
      rows: [],
      chunksReceived: 0,
      startTime: Date.now()
    });
    
    console.log(`📦 Chunked transfer initialized for ${clientName} (session: ${sessionId}, expected rows: ${totalRows})`);
    res.json({ status: 'initialized', sessionId, message: 'Chunked transfer initialized' });
  } catch (error) {
    console.error('❌ Error initializing chunked transfer:', error.message);
    res.status(500).json({ status: 'error', message: error.message });
  }
});

// Endpoint to receive a chunk of data
app.post('/report-data-chunk', (req, res) => {
  try {
    const { sessionId, chunkIndex, totalChunks, rows } = req.body;
    
    if (!sessionId || chunkIndex === undefined || !rows) {
      return res.status(400).json({ status: 'error', message: 'Missing required fields' });
    }
    
    const session = chunkedDataStore.get(sessionId);
    if (!session) {
      return res.status(404).json({ status: 'error', message: 'Session not found' });
    }
    
    // Append rows to session
    session.rows.push(...rows);
    session.chunksReceived++;
    
    console.log(`📦 Received chunk ${chunkIndex + 1}/${totalChunks} for ${session.clientName} (${rows.length} rows, total: ${session.rows.length})`);
    
    res.json({ 
      status: 'received', 
      chunkIndex, 
      totalChunks,
      rowsReceived: session.rows.length,
      message: `Chunk ${chunkIndex + 1}/${totalChunks} received` 
    });
  } catch (error) {
    console.error('❌ Error receiving chunk:', error.message);
    res.status(500).json({ status: 'error', message: error.message });
  }
});

// Endpoint to finalize chunked data transfer and save
app.post('/report-data-chunk-finalize', (req, res) => {
  try {
    const { sessionId, htmlTable } = req.body;
    
    if (!sessionId) {
      return res.status(400).json({ status: 'error', message: 'Session ID required' });
    }
    
    const session = chunkedDataStore.get(sessionId);
    if (!session) {
      return res.status(404).json({ status: 'error', message: 'Session not found' });
    }
    
    const { clientName, clientId, headers, rows, totalRows, timestamp } = session;
    const transferTime = ((Date.now() - session.startTime) / 1000).toFixed(2);
    
    console.log(`📊 Finalizing chunked transfer for ${clientName}: ${rows.length} rows received in ${transferTime}s`);
    
    // Verify we received all expected rows
    if (rows.length !== totalRows) {
      console.log(`⚠️ Row count mismatch: expected ${totalRows}, received ${rows.length}`);
    }
    
    // Create reportData object
    const reportData = {
      headers,
      rows,
      rowCount: rows.length
    };
    
    // Save to Excel and JSON (reuse existing logic)
    try {
      const excelFileName = 'report-data.xlsx';
      const excelFilePath = path.join(__dirname, excelFileName);
      
      if (fs.existsSync(excelFilePath)) {
        fs.unlinkSync(excelFilePath);
      }
      
      const worksheetData = [reportData.headers];
      reportData.rows.forEach(row => {
        const rowData = reportData.headers.map(header => row[header] || '');
        worksheetData.push(rowData);
      });
      
      const workbook = XLSX.utils.book_new();
      const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);
      
      const maxWidth = 50;
      const colWidths = reportData.headers.map(header => {
        const headerLength = header.length;
        const maxDataLength = reportData.rows.reduce((max, row) => {
          return Math.max(max, String(row[header] || '').length);
        }, headerLength);
        return { wch: Math.min(maxWidth, Math.max(headerLength, maxDataLength) + 2) };
      });
      worksheet['!cols'] = colWidths;
      
      XLSX.utils.book_append_sheet(workbook, worksheet, 'Report Data');
      
      const metadataSheet = XLSX.utils.aoa_to_sheet([
        ['Client Name', clientName],
        ['Client ID', clientId || ''],
        ['Timestamp', timestamp || new Date().toISOString()],
        ['Total Rows', reportData.rowCount],
        ['Generated At', new Date().toLocaleString()],
        ['Transfer Method', 'Chunked'],
        ['Transfer Time', `${transferTime}s`]
      ]);
      XLSX.utils.book_append_sheet(workbook, metadataSheet, 'Metadata');
      
      XLSX.writeFile(workbook, excelFilePath);
      console.log(`✅ Excel file created: ${excelFileName} (${reportData.rowCount} rows)`);
      
      // Save to JSON file in logs/json/portal directory
      const logsDir = path.join(__dirname, 'logs');
      if (!fs.existsSync(logsDir)) {
        fs.mkdirSync(logsDir, { recursive: true });
      }
      const jsonDir = path.join(logsDir, 'json', 'portal');
      if (!fs.existsSync(jsonDir)) {
        fs.mkdirSync(jsonDir, { recursive: true });
      }
      
      const sanitizedClientName = clientName.replace(/[^a-zA-Z0-9]/g, '');
      const jsonFileName = `${sanitizedClientName}-report-${Date.now()}.json`;
      const jsonFilePath = path.join(jsonDir, jsonFileName);
      
      const jsonData = {
        clientName: clientName,
        clientId: clientId || '',
        timestamp: timestamp || new Date().toISOString(),
        generatedAt: new Date().toISOString(),
        totalRows: reportData.rowCount,
        headers: reportData.headers,
        data: reportData.rows,
        transferMethod: 'chunked',
        transferTime: `${transferTime}s`
      };
      
      fs.writeFileSync(jsonFilePath, JSON.stringify(jsonData, null, 2), 'utf8');
      console.log(`✅ JSON file created: ${jsonFileName} (${reportData.rowCount} rows)`);
      console.log(`📁 JSON file path: ${jsonFilePath}`);
      
      // Save HTML table if provided
      if (htmlTable) {
        const htmlFileName = `${sanitizedClientName}-report-${Date.now()}.html`;
        const htmlFilePath = path.join(jsonDir, htmlFileName);
        const htmlContent = generateHtmlReport(clientName, clientId, reportData, timestamp, htmlTable, 'chunked', `${transferTime}s`);
        
        fs.writeFileSync(htmlFilePath, htmlContent, 'utf8');
        console.log(`✅ HTML file created: ${htmlFileName}`);
        console.log(`📁 HTML file path: ${htmlFilePath}`);
      }
      
      emitter.emit('message', { 
        type: 'info', 
        text: `📊 Excel file saved: ${excelFileName} (${reportData.rowCount} rows)\n📄 JSON file saved: ${jsonFileName} (chunked transfer, ${transferTime}s)\n` 
      });
      
      // Clean up session
      chunkedDataStore.delete(sessionId);
      
      res.json({ 
        status: 'completed', 
        message: 'Report data received and saved to Excel and JSON via chunked transfer',
        jsonFile: jsonFileName,
        rows: reportData.rowCount,
        transferTime: `${transferTime}s`
      });
    } catch (saveError) {
      chunkedDataStore.delete(sessionId);
      throw saveError;
    }
  } catch (error) {
    console.error('❌ Error finalizing chunked transfer:', error.message);
    logToFile('ERROR', `Error finalizing chunked transfer: ${error.message}`);
    res.status(500).json({ status: 'error', message: error.message });
  }
});

// Global error handler for payload too large errors
app.use((error, req, res, next) => {
  if (error.type === 'entity.too.large' || error.status === 413 || error.message?.includes('too large')) {
    console.error(`❌ Payload too large: ${error.message}`);
    logToFile('ERROR', `Payload too large error: ${error.message}`);
    res.status(413).json({ 
      status: 'error', 
      message: 'Request payload too large. Large reports are automatically sent in chunks. If you still see this error, please contact support.',
      error: 'PayloadTooLargeError',
      suggestion: 'The system should automatically use chunked transfer for large reports'
    });
  } else {
    next(error);
  }
});

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ 
    status: 'ok', 
    running: running,
    dbUpdateRunning: dbUpdateRunning,
    timestamp: new Date().toISOString()
  });
});

// Serve clients data JSON file
app.get('/clients-data-manual.json', (req, res) => {
  const jsonPath = path.join(__dirname, 'clients-data-manual.json');
  if (fs.existsSync(jsonPath)) {
    res.setHeader('Content-Type', 'application/json');
    res.sendFile(jsonPath);
  } else {
    res.status(404).json({ error: 'clients-data-manual.json not found' });
  }
});


// Comparison function: Compare DB data with Portal JSON and generate Excel
function compareDBAndPortal(dbData, portalData, clientId, clientName) {
  try {
    // Normalize data structures
    const dbRecords = Array.isArray(dbData) ? dbData : (dbData.data || []);
    const portalRecords = Array.isArray(portalData) ? portalData : (portalData.data || []);
    
    // Create a mapping function to normalize field names - updated to match new query schema
    const normalizeDBRecord = (record) => {
      const storeName = String(record.StoreName || '').trim();
      const userName = String(record.UserName || '').trim();
      return {
        RM: String(record.RM || '').trim(),
        DM: String(record.DM || '').trim(),
        StoreName: storeName,
        UserName: userName,
        CameraNetHours: parseFloat(record.CameraNetHours) || 0,
        MonitoredPercent: parseFloat(record.MonitoredPercent) || 0,
        // Create unique key: StoreName + UserName (case-insensitive)
        uniqueKey: `${storeName.toLowerCase()}_${userName.toLowerCase()}`
      };
    };
    
    const normalizePortalRecord = (record) => {
      const storeName = String(record.StoreName || '').trim();
      const userName = String(record.UserName || '').trim();
      return {
        RM: String(record.RM || '').trim(),
        DM: String(record.DM || '').trim(),
        StoreName: storeName,
        UserName: userName,
        CameraNetHours: parseFloat(record.CameraNetHours) || 0,
        MonitoredPercent: parseFloat(record.MonitoredPercent) || 0,
        // Create unique key: StoreName + UserName (case-insensitive)
        uniqueKey: `${storeName.toLowerCase()}_${userName.toLowerCase()}`
      };
    };
    
    // Helper function to check if a record should be filtered out (header/total rows)
    const shouldFilterRecord = (record) => {
      const userName = String(record.UserName || '').trim().toLowerCase();
      const storeName = String(record.StoreName || '').trim().toLowerCase();
      const rm = String(record.RM || '').trim().toLowerCase();
      const dm = String(record.DM || '').trim().toLowerCase();
      
      // Skip rows without UserName (header/total rows or rowspan continuation)
      if (!userName || userName.length === 0) {
        return true;
      }
      
      // Skip total rows
      if (userName.includes('total') || storeName.includes('total')) {
        return true;
      }
      
      // Skip header rows - check if values match common header column names
      const headerValues = ['rm', 'dm', 'store name', 'storename', 'user name', 'username', 
                           'camera net hours', 'cameranethours', 'monitored', 'monitoredpercent',
                           'monitored percent', 'monitored days', 'total days'];
      if (headerValues.includes(userName) || headerValues.includes(storeName) || 
          headerValues.includes(rm) || headerValues.includes(dm)) {
        return true;
      }
      
      return false;
    };
    
    // Normalize all records
    const normalizedDB = dbRecords.map(normalizeDBRecord);
    const normalizedPortal = portalRecords.map(normalizePortalRecord);
    
    // Filter out header/total rows before comparison
    const filteredDB = normalizedDB.filter(record => !shouldFilterRecord(record));
    const filteredPortal = normalizedPortal.filter(record => !shouldFilterRecord(record));
    
    console.log(`📊 Filtered records: DB ${normalizedDB.length} → ${filteredDB.length}, Portal ${normalizedPortal.length} → ${filteredPortal.length}`);
    
    // Create maps for quick lookup
    const dbMap = new Map();
    filteredDB.forEach(record => {
      dbMap.set(record.uniqueKey, record);
    });
    
    const portalMap = new Map();
    filteredPortal.forEach(record => {
      portalMap.set(record.uniqueKey, record);
    });
    
    // Get all unique keys
    const allKeys = new Set([...dbMap.keys(), ...portalMap.keys()]);
    
    // Build comparison results
    const differences = [];
    const dbOnly = [];
    const portalOnly = [];
    
    allKeys.forEach(key => {
      const dbRecord = dbMap.get(key);
      const portalRecord = portalMap.get(key);
      
      if (!dbRecord && portalRecord) {
        // Only in portal
        portalOnly.push({
          uniqueKey: key,
          StoreName: portalRecord.StoreName,
          UserName: portalRecord.UserName,
          ...portalRecord
        });
        differences.push({
          uniqueKey: key,
          status: 'PORTAL_ONLY',
          comparisonSummary: 'Record exists only in Portal data',
          RM: portalRecord.RM,
          DM: portalRecord.DM,
          StoreName: portalRecord.StoreName,
          UserName: portalRecord.UserName,
          CameraNetHours: portalRecord.CameraNetHours,
          MonitoredPercent: portalRecord.MonitoredPercent
        });
      } else if (dbRecord && !portalRecord) {
        // Only in DB
        dbOnly.push({
          uniqueKey: key,
          StoreName: dbRecord.StoreName,
          UserName: dbRecord.UserName,
          ...dbRecord
        });
        differences.push({
          uniqueKey: key,
          status: 'DB_ONLY',
          comparisonSummary: 'Record exists only in DB data',
          RM: dbRecord.RM,
          DM: dbRecord.DM,
          StoreName: dbRecord.StoreName,
          UserName: dbRecord.UserName,
          CameraNetHours: dbRecord.CameraNetHours,
          MonitoredPercent: dbRecord.MonitoredPercent
        });
      } else if (dbRecord && portalRecord) {
        // Compare only the specified fields: RM, DM, StoreName, UserName, CameraNetHours, MonitoredPercent
        const mismatches = [];
        
        // Compare each field
        const fieldsToCompare = [
          { name: 'RM', dbValue: dbRecord.RM, portalValue: portalRecord.RM },
          { name: 'DM', dbValue: dbRecord.DM, portalValue: portalRecord.DM },
          { name: 'StoreName', dbValue: dbRecord.StoreName, portalValue: portalRecord.StoreName },
          { name: 'UserName', dbValue: dbRecord.UserName, portalValue: portalRecord.UserName },
          { name: 'CameraNetHours', dbValue: dbRecord.CameraNetHours, portalValue: portalRecord.CameraNetHours },
          { name: 'MonitoredPercent', dbValue: dbRecord.MonitoredPercent, portalValue: portalRecord.MonitoredPercent }
        ];
        
        fieldsToCompare.forEach(field => {
          let dbVal = field.dbValue;
          let portalVal = field.portalValue;
          
          // Handle numeric fields
          if (field.name === 'CameraNetHours' || field.name === 'MonitoredPercent') {
            const dbNum = parseFloat(dbVal) || 0;
            const portalNum = parseFloat(portalVal) || 0;
            if (Math.abs(dbNum - portalNum) > 0.01) { // Allow small floating point differences
              mismatches.push(`${field.name}: DB="${dbNum}" Portal="${portalNum}"`);
            }
          } else {
            // String comparison
            const dbStr = String(dbVal || '').trim().toLowerCase();
            const portalStr = String(portalVal || '').trim().toLowerCase();
            if (dbStr !== portalStr) {
              mismatches.push(`${field.name}: DB="${dbVal}" Portal="${portalVal}"`);
            }
          }
        });
        
        if (mismatches.length > 0) {
          differences.push({
            uniqueKey: key,
            status: 'DIFFERENT',
            comparisonSummary: mismatches.join('; '),
            RM: dbRecord.RM,
            DM: dbRecord.DM,
            StoreName: dbRecord.StoreName || portalRecord.StoreName,
            UserName: dbRecord.UserName,
            CameraNetHours: dbRecord.CameraNetHours,
            MonitoredPercent: dbRecord.MonitoredPercent,
            portal_RM: portalRecord.RM,
            portal_DM: portalRecord.DM,
            portal_StoreName: portalRecord.StoreName,
            portal_UserName: portalRecord.UserName,
            portal_CameraNetHours: portalRecord.CameraNetHours,
            portal_MonitoredPercent: portalRecord.MonitoredPercent
          });
        }
      }
    });
    
    // Create Excel workbook with 3 sheets - only showing specified columns
    const workbook = XLSX.utils.book_new();
    
    // Sheet 1: DB Data - only specified columns (filtered)
    const dbHeaders = ['RM', 'DM', 'StoreName', 'UserName', 'CameraNetHours', 'MonitoredPercent'];
    const dbSheetData = [dbHeaders];
    filteredDB.forEach(record => {
      dbSheetData.push(dbHeaders.map(header => record[header] || ''));
    });
    const dbWorksheet = XLSX.utils.aoa_to_sheet(dbSheetData);
    XLSX.utils.book_append_sheet(workbook, dbWorksheet, 'DB Data');
    
    // Sheet 2: Portal Data - only specified columns (filtered)
    const portalHeaders = ['RM', 'DM', 'StoreName', 'UserName', 'CameraNetHours', 'MonitoredPercent'];
    const portalSheetData = [portalHeaders];
    filteredPortal.forEach(record => {
      portalSheetData.push(portalHeaders.map(header => record[header] || ''));
    });
    const portalWorksheet = XLSX.utils.aoa_to_sheet(portalSheetData);
    XLSX.utils.book_append_sheet(workbook, portalWorksheet, 'Portal Data');
    
    // Sheet 3: Differences - only specified columns plus status and comparison summary
    const diffHeaders = ['status', 'RM', 'DM', 'StoreName', 'UserName', 'CameraNetHours', 'MonitoredPercent',
                         'portal_RM', 'portal_DM', 'portal_StoreName', 'portal_UserName', 'portal_CameraNetHours', 
                         'portal_MonitoredPercent', 'comparisonSummary'];
    const diffSheetData = [diffHeaders];
    
    differences.forEach(diff => {
      const row = diffHeaders.map(header => {
        if (header === 'comparisonSummary') {
          return diff[header] || '';
        }
        return diff[header] || '';
      });
      diffSheetData.push(row);
    });
    
    const diffWorksheet = XLSX.utils.aoa_to_sheet(diffSheetData);
    
    // Apply basic styling to highlight differences (XLSX has limited styling support)
    // Note: Full styling may not work in all Excel readers, but data will be present
    const range = XLSX.utils.decode_range(diffWorksheet['!ref'] || 'A1');
    for (let R = 1; R <= range.e.r; R++) {
      const diff = differences[R - 1];
      if (diff) {
        // Add status indicator in first column for visual identification
        const statusCell = XLSX.utils.encode_cell({ r: R, c: 0 });
        if (diffWorksheet[statusCell]) {
          // Add comment or prefix to status for identification
          const statusPrefix = diff.status === 'DIFFERENT' ? '⚠️ ' : 
                              diff.status === 'DB_ONLY' ? '🔴 ' : 
                              diff.status === 'PORTAL_ONLY' ? '🟢 ' : '';
          if (statusPrefix && !diffWorksheet[statusCell].v?.startsWith(statusPrefix)) {
            diffWorksheet[statusCell].v = statusPrefix + (diffWorksheet[statusCell].v || diff.status);
          }
        }
      }
    }
    
    // Set column widths
    const colWidths = diffHeaders.map((header, idx) => {
      if (header === 'comparisonSummary') {
        return { wch: 80 }; // Wider for summary
      }
      if (header === 'status') {
        return { wch: 15 };
      }
      if (header.startsWith('portal_')) {
        return { wch: 18 }; // Slightly narrower for portal columns
      }
      return { wch: 20 };
    });
    diffWorksheet['!cols'] = colWidths;
    
    XLSX.utils.book_append_sheet(workbook, diffWorksheet, 'Differences');
    
    // Save Excel file
    const sanitizedClientName = clientName.replace(/[^a-zA-Z0-9]/g, '_');
    const excelFileName = `${sanitizedClientName}-comparison-${clientId}-${Date.now()}.xlsx`;
    const logsDir = path.join(__dirname, 'logs');
    if (!fs.existsSync(logsDir)) {
      fs.mkdirSync(logsDir, { recursive: true });
    }
    const excelDir = path.join(logsDir, 'comparison');
    if (!fs.existsSync(excelDir)) {
      fs.mkdirSync(excelDir, { recursive: true });
    }
    const excelFilePath = path.join(excelDir, excelFileName);
    
    XLSX.writeFile(workbook, excelFilePath);
    
    return {
      success: true,
      filePath: excelFilePath,
      fileName: excelFileName,
      stats: {
        totalDBRecords: filteredDB.length,
        totalPortalRecords: filteredPortal.length,
        differences: differences.length,
        dbOnly: dbOnly.length,
        portalOnly: portalOnly.length,
        matching: filteredDB.length - differences.filter(d => d.status === 'DIFFERENT' || d.status === 'DB_ONLY').length
      }
    };
  } catch (error) {
    console.error('❌ Error in comparison function:', error);
    return {
      success: false,
      error: error.message
    };
  }
}

// Endpoint to compare DB and Portal data
app.post('/compare-data', async (req, res) => {
  try {
    console.log(`📥 Received POST /compare-data request`);
    console.log(`📦 Request body:`, JSON.stringify(req.body, null, 2));
    
    const { clientId, clientName } = req.body;
    
    if (!clientId) {
      console.error('❌ Missing clientId in request');
      return res.status(400).json({ status: 'error', message: 'clientId is required' });
    }
    
    if (!clientName) {
      console.error('❌ Missing clientName in request');
      return res.status(400).json({ status: 'error', message: 'clientName is required' });
    }
    
    console.log(`🔍 Starting comparison for client: ${clientName} (ID: ${clientId})`);
    
    // Load DB data - try multiple sanitization approaches for client name matching
    const sanitizedClientName1 = clientName.replace(/[^a-zA-Z0-9]/g, '');
    const sanitizedClientName2 = clientName.replace(/[^a-zA-Z0-9]/g, '_');
    
    // Try to find DB file with different naming patterns
    let dbFilePath = path.join(__dirname, 'logs', 'json', 'db', `${sanitizedClientName1}.json`);
    if (!fs.existsSync(dbFilePath)) {
        // Try alternative naming
        dbFilePath = path.join(__dirname, 'logs', 'json', 'db', `${sanitizedClientName2}.json`);
        if (!fs.existsSync(dbFilePath)) {
          // Try to find any file that contains the client name
          const dbDir = path.join(__dirname, 'logs', 'json', 'db');
        const dbFiles = fs.readdirSync(dbDir)
          .filter(file => file.endsWith('.json'))
          .map(file => ({
            name: file,
            path: path.join(dbDir, file),
            data: JSON.parse(fs.readFileSync(path.join(dbDir, file), 'utf8'))
          }))
          .find(file => {
            const clientNameInFile = file.data.clientName || '';
            return clientNameInFile.toLowerCase() === clientName.toLowerCase() ||
                   clientNameInFile.replace(/[^a-zA-Z0-9]/g, '').toLowerCase() === sanitizedClientName1.toLowerCase();
          });
        
        if (dbFiles) {
          dbFilePath = dbFiles.path;
        } else {
          return res.status(404).json({ status: 'error', message: `DB file not found for ${clientName}. Tried: ${sanitizedClientName1}.json and ${sanitizedClientName2}.json` });
        }
      }
    }
    
    const dbData = JSON.parse(fs.readFileSync(dbFilePath, 'utf8'));
    
    // Find latest portal JSON file for this client - try multiple matching approaches
    const portalDir = path.join(__dirname, 'logs', 'json', 'portal');
    const allPortalFiles = fs.readdirSync(portalDir)
      .filter(file => file.endsWith('.json'))
      .map(file => ({
        name: file,
        path: path.join(portalDir, file),
        time: fs.statSync(path.join(portalDir, file)).mtime.getTime(),
        data: JSON.parse(fs.readFileSync(path.join(portalDir, file), 'utf8'))
      }));
    
    // Try to match by filename first
    let portalFiles = allPortalFiles.filter(file => {
      const fileNameLower = file.name.toLowerCase();
      const clientNameLower = clientName.toLowerCase();
      const sanitized1 = sanitizedClientName1.toLowerCase();
      const sanitized2 = sanitizedClientName2.toLowerCase();
      
      return fileNameLower.includes(sanitized1) || 
             fileNameLower.includes(sanitized2) ||
             fileNameLower.includes(clientNameLower.replace(/[^a-zA-Z0-9]/g, '').toLowerCase());
    });
    
    // If no match by filename, try matching by clientName in JSON data
    if (portalFiles.length === 0) {
      portalFiles = allPortalFiles.filter(file => {
        const clientNameInFile = (file.data.clientName || '').toLowerCase();
        return clientNameInFile === clientName.toLowerCase() ||
               clientNameInFile.replace(/[^a-zA-Z0-9]/g, '').toLowerCase() === sanitizedClientName1.toLowerCase();
      });
    }
    
    portalFiles.sort((a, b) => b.time - a.time);
    
    if (portalFiles.length === 0) {
      return res.status(404).json({ status: 'error', message: `No portal data found for ${clientName}. Searched in ${portalDir}` });
    }
    
    const portalData = portalFiles[0].data;
    
    // Perform comparison
    const result = compareDBAndPortal(dbData, portalData, clientId, clientName);
    
    if (!result.success) {
      return res.status(500).json({ status: 'error', message: result.error });
    }
    
    console.log(`✅ Comparison completed for ${clientName}:`, result.stats);
    
    // Save comparison metadata to logs
    const logsDir = path.join(__dirname, 'logs');
    if (!fs.existsSync(logsDir)) {
      fs.mkdirSync(logsDir, { recursive: true });
    }
    const metadataDir = path.join(logsDir, 'metadata');
    if (!fs.existsSync(metadataDir)) {
      fs.mkdirSync(metadataDir, { recursive: true });
    }
    
    const metadata = {
      clientId: clientId,
      clientName: clientName,
      timestamp: new Date().toISOString(),
      runTimestamp: Date.now(),
      status: result.success ? 'success' : 'failed',
      fileName: result.fileName,
      filePath: result.filePath,
      stats: result.stats,
      differencesCount: result.stats?.differences || 0,
      dbOnlyCount: result.stats?.dbOnly || 0,
      portalOnlyCount: result.stats?.portalOnly || 0,
      matchingCount: result.stats?.matching || 0,
      totalDBRecords: result.stats?.totalDBRecords || 0,
      totalPortalRecords: result.stats?.totalPortalRecords || 0
    };
    
    const metadataFileName = `${clientName.replace(/[^a-zA-Z0-9]/g, '_')}-${clientId}-${Date.now()}.json`;
    const metadataFilePath = path.join(metadataDir, metadataFileName);
    fs.writeFileSync(metadataFilePath, JSON.stringify(metadata, null, 2), 'utf8');
    
    res.json({
      status: 'success',
      message: 'Comparison completed successfully',
      filePath: result.filePath,
      fileName: result.fileName,
      stats: result.stats,
      clientId: clientId,
      clientName: clientName,
      metadata: metadata
    });
    
  } catch (error) {
    console.error('❌ Error in compare-data endpoint:', error);
    res.status(500).json({ status: 'error', message: error.message });
  }
});

// Endpoint to list all logs
app.get('/logs', (req, res) => {
  try {
    const metadataDir = path.join(__dirname, 'logs', 'metadata');
    if (!fs.existsSync(metadataDir)) {
      return res.json({ logs: [] });
    }
    
    const metadataFiles = fs.readdirSync(metadataDir)
      .filter(file => file.endsWith('.json'))
      .map(file => {
        try {
          const filePath = path.join(metadataDir, file);
          const metadata = JSON.parse(fs.readFileSync(filePath, 'utf8'));
          return {
            ...metadata,
            metadataFile: file
          };
        } catch (error) {
          console.error(`Error reading metadata file ${file}:`, error.message);
          return null;
        }
      })
      .filter(metadata => metadata !== null)
      .sort((a, b) => b.runTimestamp - a.runTimestamp); // Sort by newest first
    
    res.json({ logs: metadataFiles });
    
  } catch (error) {
    console.error('❌ Error listing logs:', error);
    res.status(500).json({ status: 'error', message: error.message });
  }
});

// Endpoint to download comparison Excel file
app.get('/download-comparison/:clientId', (req, res) => {
  try {
    const { clientId } = req.params;
    
    // Find the latest comparison file for this client
    const comparisonDir = path.join(__dirname, 'logs', 'comparison');
    if (!fs.existsSync(comparisonDir)) {
      return res.status(404).json({ status: 'error', message: 'Comparison directory not found' });
    }
    
    const comparisonFiles = fs.readdirSync(comparisonDir)
      .filter(file => file.includes(`-${clientId}-`) && file.endsWith('.xlsx'))
      .map(file => ({
        name: file,
        path: path.join(comparisonDir, file),
        time: fs.statSync(path.join(comparisonDir, file)).mtime.getTime()
      }))
      .sort((a, b) => b.time - a.time);
    
    if (comparisonFiles.length === 0) {
      return res.status(404).json({ status: 'error', message: `No comparison file found for client ID ${clientId}` });
    }
    
    const filePath = comparisonFiles[0].path;
    const fileName = comparisonFiles[0].name;
    
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
    res.sendFile(filePath);
    
  } catch (error) {
    console.error('❌ Error downloading comparison file:', error);
    res.status(500).json({ status: 'error', message: error.message });
  }
});

// Serve static files (must be after API routes)
app.use(express.static('.'));

// Serve the main HTML file
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});

// 404 handler for API routes (must be last, after all routes and static files)
app.use((req, res, next) => {
  // Only handle 404s for API routes (not static files or HTML)
  const isApiRoute = req.path.startsWith('/compare-data') || 
                     req.path.startsWith('/download-comparison') || 
                     req.path.startsWith('/run-tests') || 
                     req.path.startsWith('/report-data') || 
                     req.path.startsWith('/update-client-data') ||
                     req.path.startsWith('/events') ||
                     req.path.startsWith('/health') ||
                     req.path.startsWith('/logs');
  
  if (isApiRoute) {
    // This means no route matched - return JSON error
    return res.status(404).json({ 
      status: 'error', 
      message: `Route not found: ${req.method} ${req.path}. Please ensure the server has been restarted with the latest code.`,
      availableRoutes: [
        'POST /compare-data',
        'GET /download-comparison/:clientId',
        'POST /run-tests',
        'POST /report-data',
        'POST /report-data-chunk-start',
        'POST /report-data-chunk',
        'POST /report-data-chunk-finalize',
        'POST /update-client-data',
        'GET /events',
        'GET /health',
        'GET /logs'
      ]
    });
  }
  // For non-API routes, let Express handle 404 naturally
  res.status(404).send('Not Found');
});

const PORT = process.env.PORT || 3010;

// Start server
function startServer() {
  // Add global error handlers to catch and log all errors
  process.on('uncaughtException', (error) => {
    const errorMsg = `Uncaught Exception: ${error.message}\nStack: ${error.stack}`;
    console.error('❌', errorMsg);
    logToFile('ERROR', errorMsg);
  });
  
  process.on('unhandledRejection', (reason, promise) => {
    const errorMsg = `Unhandled Rejection at: ${promise}\nReason: ${reason}`;
    console.error('❌', errorMsg);
    logToFile('ERROR', errorMsg);
  });
  
  app.listen(PORT, () => {
    console.log('==========================================');
    console.log('Employee Camera Hours Dashboard');
    console.log('==========================================\n');
    console.log(`🚀 Playwright Test Server running on http://localhost:${PORT}`);
    console.log(`📝 Server logs are being written to: ${logFilePath}`);
    console.log('📋 Available endpoints:');
    console.log('   GET  /events - Server-Sent Events stream');
    console.log('   POST /run-tests - Start Playwright tests');
    console.log('   POST /update-client-data - Update client data from database');
    console.log('   POST /report-data - Receive report data (single request)');
    console.log('   POST /report-data-chunk-start - Initialize chunked transfer');
    console.log('   POST /report-data-chunk - Receive chunk of data');
    console.log('   POST /report-data-chunk-finalize - Finalize chunked transfer');
    console.log('   ✅ POST /compare-data - Compare DB and Portal data, generate Excel');
    console.log('   ✅ GET  /download-comparison/:clientId - Download comparison Excel file');
    console.log('   ✅ GET  /logs - List all comparison logs');
    console.log('   GET  /health - Health check');
    console.log('   GET  /clients-data-manual.json - Client data file');
    console.log('   GET  / - Main dashboard');
    console.log('\n✅ All routes registered successfully!');
    console.log('Press Ctrl+C to stop the server\n');
    logToFile('INFO', `Server started on port ${PORT} - All routes registered`);
    
    // Run database update on server startup
    console.log('🔄 Running database update on startup...');
    fetchClientData()
      .then((clientsData) => {
        console.log(`✅ Database update completed on startup. Updated ${clientsData.length} clients.`);
        logToFile('INFO', `Database update completed on startup. ${clientsData.length} clients updated.`);
      })
      .catch((error) => {
        console.warn(`⚠️  Database update on startup failed: ${error.message}`);
        console.warn('   The server will continue running. You can update manually via /update-client-data endpoint.');
        logToFile('WARN', `Database update on startup failed: ${error.message}`);
      });
  });
}

startServer();

// Graceful shutdown
process.on('SIGINT', () => {
  console.log('\n🛑 Shutting down server...');
  process.exit(0);
});